module.exports = {
  time: {start: 4, length: 8, description: 'Time elapsed since the controller was started'},
  tarJ1pos: {start: 12, length: 8, description: 'Target joint 1 position'},
  tarJ2pos: {start: 20, length: 8, description: 'Target joint 2 position'},
  tarJ3pos: {start: 28, length: 8, description: 'Target joint 3 position'},
  tarJ4pos: {start: 36, length: 8, description: 'Target joint 4 position'},
  tarJ5pos: {start: 44, length: 8, description: 'Target joint 5 position'},
  tarJ6pos: {start: 52, length: 8, description: 'Target joint 6 position'},
  tarJ1vel: {start: 60, length: 8, description: 'Target joint 1 velocity'},
  tarJ2vel: {start: 68, length: 8, description: 'Target joint 2 velocity'},
  tarJ3vel: {start: 76, length: 8, description: 'Target joint 3 velocity'},
  tarJ4vel: {start: 84, length: 8, description: 'Target joint 4 velocity'},
  tarJ5vel: {start: 92, length: 8, description: 'Target joint 5 velocity'},
  tarJ6vel: {start: 100, length: 8, description: 'Target joint 6 velocity'},
  tarJ1acc: {start: 108, length: 8, description: 'Target joint 1 acceleration'},
  tarJ2acc: {start: 116, length: 8, description: 'Target joint 2 acceleration'},
  tarJ3acc: {start: 124, length: 8, description: 'Target joint 3 acceleration'},
  tarJ4acc: {start: 132, length: 8, description: 'Target joint 4 acceleration'},
  tarJ5acc: {start: 140, length: 8, description: 'Target joint 5 acceleration'},
  tarJ6acc: {start: 148, length: 8, description: 'Target joint 6 acceleration'},
  tarJ1cur: {start: 156, length: 8, description: 'Target joint 1 current'},
  tarJ2cur: {start: 164, length: 8, description: 'Target joint 2 current'},
  tarJ3cur: {start: 172, length: 8, description: 'Target joint 3 current'},
  tarJ4cur: {start: 180, length: 8, description: 'Target joint 4 current'},
  tarJ5cur: {start: 188, length: 8, description: 'Target joint 5 current'},
  tarJ6cur: {start: 196, length: 8, description: 'Target joint 6 current'},
  tarJ1mom: {start: 204, length: 8, description: 'Target joint 1 moment (torque)'},
  tarJ2mom: {start: 212, length: 8, description: 'Target joint 2 moment (torque)'},
  tarJ3mom: {start: 220, length: 8, description: 'Target joint 3 moment (torque)'},
  tarJ4mom: {start: 228, length: 8, description: 'Target joint 4 moment (torque)'},
  tarJ5mom: {start: 236, length: 8, description: 'Target joint 5 moment (torque)'},
  tarJ6mom: {start: 244, length: 8, description: 'Target joint 6 moment (torque)'},
  actJ1pos: {start: 252, length: 8, description: 'Actual joint 1 position'},
  actJ2pos: {start: 260, length: 8, description: 'Actual joint 2 position'},
  actJ3pos: {start: 268, length: 8, description: 'Actual joint 3 position'},
  actJ4pos: {start: 276, length: 8, description: 'Actual joint 4 position'},
  actJ5pos: {start: 284, length: 8, description: 'Actual joint 5 position'},
  actJ6pos: {start: 292, length: 8, description: 'Actual joint 6 position'},
  actJ1vel: {start: 300, length: 8, description: 'Actual joint 1 velocity'},
  actJ2vel: {start: 308, length: 8, description: 'Actual joint 2 velocity'},
  actJ3vel: {start: 316, length: 8, description: 'Actual joint 3 velocity'},
  actJ4vel: {start: 324, length: 8, description: 'Actual joint 4 velocity'},
  actJ5vel: {start: 332, length: 8, description: 'Actual joint 5 velocity'},
  actJ6vel: {start: 340, length: 8, description: 'Actual joint 6 velocity'},
  actJ1cur: {start: 348, length: 8, description: 'Actual joint 1 current'},
  actJ2cur: {start: 356, length: 8, description: 'Actual joint 2 current'},
  actJ3cur: {start: 364, length: 8, description: 'Actual joint 3 current'},
  actJ4cur: {start: 372, length: 8, description: 'Actual joint 4 current'},
  actJ5cur: {start: 380, length: 8, description: 'Actual joint 5 current'},
  actJ6cur: {start: 388, length: 8, description: 'Actual joint 6 current'},
  conJ1cur: {start: 396, length: 8, description: 'Joint 1 control current'},
  conJ2cur: {start: 404, length: 8, description: 'Joint 2 control current'},
  conJ3cur: {start: 412, length: 8, description: 'Joint 3 control current'},
  conJ4cur: {start: 420, length: 8, description: 'Joint 4 control current'},
  conJ5cur: {start: 428, length: 8, description: 'Joint 5 control current'},
  conJ6cur: {start: 436, length: 8, description: 'Joint 6 control current'},
  actXXpos: {start: 444, length: 8, description: 'Actual Cartesian coordinate of the tool: x'},
  actYYpos: {start: 452, length: 8, description: 'Actual Cartesian coordinate of the tool: y'},
  actZZpos: {start: 460, length: 8, description: 'Actual Cartesian coordinate of the tool: z'},
  actRXpos: {start: 468, length: 8, description: 'Actual Cartesian coordinate of the tool: rx'},
  actRYpos: {start: 476, length: 8, description: 'Actual Cartesian coordinate of the tool: ry'},
  actRZpos: {start: 484, length: 8, description: 'Actual Cartesian coordinate of the tool: rz'},
  actXXvel: {start: 492, length: 8, description: 'Actual speed of the tool given in Cartesian coordinate: x'},
  actYYvel: {start: 500, length: 8, description: 'Actual speed of the tool given in Cartesian coordinate: y'},
  actZZvel: {start: 508, length: 8, description: 'Actual speed of the tool given in Cartesian coordinate: z'},
  actRXvel: {start: 516, length: 8, description: 'Actual speed of the tool given in Cartesian coordinate: rx'},
  actRYvel: {start: 524, length: 8, description: 'Actual speed of the tool given in Cartesian coordinate: ry'},
  actRZvel: {start: 532, length: 8, description: 'Actual speed of the tool given in Cartesian coordinate: rz'},
  genXXfor: {start: 540, length: 8, description: 'Generalised force in the TCP: x'},
  genYYfor: {start: 548, length: 8, description: 'Generalised force in the TCP: y'},
  genZZfor: {start: 556, length: 8, description: 'Generalised force in the TCP: z'},
  genRXfor: {start: 564, length: 8, description: 'Generalised force in the TCP: rx'},
  genRYfor: {start: 572, length: 8, description: 'Generalised force in the TCP: ry'},
  genRZfor: {start: 580, length: 8, description: 'Generalised force in the TCP: rz'},
  tarXXpos: {start: 588, length: 8, description: 'Target Cartesian coordinate of the tool: x'},
  tarYYpos: {start: 596, length: 8, description: 'Target Cartesian coordinate of the tool: y'},
  tarZZpos: {start: 604, length: 8, description: 'Target Cartesian coordinate of the tool: z'},
  tarRXpos: {start: 612, length: 8, description: 'Target Cartesian coordinate of the tool: rx'},
  tarRYpos: {start: 620, length: 8, description: 'Target Cartesian coordinate of the tool: ry'},
  tarRZpos: {start: 628, length: 8, description: 'Target Cartesian coordinate of the tool: rz'},
  tarXXvel: {start: 636, length: 8, description: 'Target speed of the tool given in Cartesian coordinate: x'},
  tarYYvel: {start: 644, length: 8, description: 'Target speed of the tool given in Cartesian coordinate: y'},
  tarZZvel: {start: 652, length: 8, description: 'Target speed of the tool given in Cartesian coordinate: z'},
  tarRXvel: {start: 660, length: 8, description: 'Target speed of the tool given in Cartesian coordinate: rx'},
  tarRYvel: {start: 668, length: 8, description: 'Target speed of the tool given in Cartesian coordinate: ry'},
  tarRZvel: {start: 676, length: 8, description: 'Target speed of the tool given in Cartesian coordinate: rz'},
  digInput: {start: 684, length: 8, description: 'Current state of the digital inputs. NOTE: these are bits encoded as int64_t, e.g. a value of 5 corresponds to bit 0 and bit 2 set high'},
  actJ1cel: {start: 692, length: 8, description: 'Temperature of joint 1 in degree celsius'},
  actJ2cel: {start: 700, length: 8, description: 'Temperature of joint 2 in degree celsius'},
  actJ3cel: {start: 708, length: 8, description: 'Temperature of joint 3 in degree celsius'},
  actJ4cel: {start: 716, length: 8, description: 'Temperature of joint 4 in degree celsius'},
  actJ5cel: {start: 724, length: 8, description: 'Temperature of joint 5 in degree celsius'},
  actJ6cel: {start: 732, length: 8, description: 'Temperature of joint 6 in degree celsius'},
  contimer: {start: 740, length: 8, description: 'Controller realtime thread execution time'},
  testVal: {start: 748, length: 8, description: 'A value used by Universal Robots software only'},
  robotMode: {start: 756, length: 8, description: 'Robot mode'},
  j1Mode: {start: 764, length: 8, description: 'Joint 1 control mode'},
  j2Mode: {start: 772, length: 8, description: 'Joint 2 control mode'},
  j3Mode: {start: 780, length: 8, description: 'Joint 3 control mode'},
  j4Mode: {start: 788, length: 8, description: 'Joint 4 control mode'},
  j5Mode: {start: 796, length: 8, description: 'Joint 5 control mode'},
  j6Mode: {start: 804, length: 8, description: 'Joint 6 control mode'},
  safetyMode: {start: 812, length: 8, description: 'Safety mode'},
  toolXacc: {start: 868, length: 8, description: 'Tool x accelerometer value (software version 1.7)'},
  toolYacc: {start: 876, length: 8, description: 'Tool y accelerometer value (software version 1.7)'},
  toolZacc: {start: 884, length: 8, description: 'Tool z accelerometer value (software version 1.7)'},
  speedScaling: {start: 940, length: 8, description: 'Speed scaling of the trajectory limiter'},
  linMomNorm: {start: 948, length: 8, description: 'Norm of Cartesian linear momentum'},
  mainV: {start: 972, length: 8, description: 'Masterboard: Main voltage'},
  robotV: {start: 980, length: 8, description: 'Masterboard: Robot voltage (48V)'},
  robotI: {start: 988, length: 8, description: 'Masterboard: Robot current'},
  actJ1V: {start: 996, length: 8, description: 'Actual joint 1 voltage'},
  actJ2V: {start: 1004, length: 8, description: 'Actual joint 2 voltage'},
  actJ3V: {start: 1012, length: 8, description: 'Actual joint 3 voltage'},
  actJ4V: {start: 1020, length: 8, description: 'Actual joint 4 voltage'},
  actJ5V: {start: 1028, length: 8, description: 'Actual joint 5 voltage'},
  actJ6V: {start: 1036, length: 8, description: 'Actual joint 6 voltage'},
  digOutput: {start: 1044, length: 8, description: 'Digital outputs'},
  progState: {start: 1052, length: 8, description: 'Program state'}
}
